### ISSUE TITLE
Allman coding style

### ISSUE THREAD

**Issue by claudemr** [rclement/launchtime#1]
I see you're using that ugly Allman coding style with bracket on its own single line... Uuuh, I suggest you use THE proper good old fashion way, the K&R style, man, because, you know, that's the way you should code your stuff, shit man, as it ever occurred to you that... I mean... com'on!

**Comment by rclement** [comment]
I know I know... The battle rages on!
To be honest, this project is a reboot from something I started more than a year ago. So for now I just grabbed the old code and put it in place. I'll perform a proper code cleanup soon!
BUT, because there is always a "but", here is what Stroustrup says about C++ coding style:

> Don't use C coding standards (even if slightly modified for C++) and don't use ten-year-old C++ coding standards (even if good for their time). C++ isn't (just) C and Standard C++ is not (just) pre-standard C++.

**Comment by rclement** [comment]
Issue fixed in commit 8cb4845a39bf45293a5dada98ef7f5e319fc187e.

AStyle code formatter has been used :
`$ astyle --style=linux <files>`
(note: K&R style for C++ is just bad... ;) )
